### ISSUE TITLE
Access API cannot get space/info

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/w3protocol#243]
```
invocation verification failed {
  name: 'Unauthorized',
  cause: {
    name: 'InvalidClaim',
    error: true,
    stack: 'InvalidClaim: Claimed capability {"can":"space/info","with":"did:key:z6MkvKqE5ft62Uxqts9pmpWEZYqybgkLUMbKt1LgSkK1aNQz"} is invalid\n' +
      "  - Capability can not be (self) issued by 'did:key:z6MkhcbEpJpEvNVDd3n5RurquVdqs5dPU16JDU5VZTDtFgnn'\n" +
      '  - Delegated capability not found\n' +
      '  - Encountered unknown capabilities\n' +
      '    - {"nb":{"link":{"code":514,"version":1,"hash":{"0":18,"1":32,"2":26,"3":58,"4":168,"5":146,"6":239,"7":237,"8":138,"9":216,"10":183,"11":37,"12":84,"13":117,"14":196,"15":48,"16":169,"17":219,"18":238,"19":43,"20":58,"21":6,"22":80,"23":147,"24":195,"25":200,"26":28,"27":71,"28":17,"29":104,"30":151,"31":80,"32":130,"33":75}},"size":47243},"can":"store/add","with":"did:key:z6MkvKqE5ft62Uxqts9pmpWEZYqybgkLUMbKt1LgSkK1aNQz"}\n' +
      '    at Fh (d1-beta-facade.entry.js:7237:10)\n' +
      '    at async Mh (d1-beta-facade.entry.js:7202:13)\n' +
      '    at async Object.info (d1-beta-facade.entry.js:8206:11)\n' +
      '    at async dx (d1-beta-facade.entry.js:8148:12)\n' +
      '    at async lx (d1-beta-facade.entry.js:8136:12)\n' +
      '    at async fx (d1-beta-facade.entry.js:8130:42)\n' +
      '    at async fg (d1-beta-facade.entry.js:9039:11)\n' +
      '    at async Bo.fetch (d1-beta-facade.entry.js:3685:17)\n' +
      '    at async Object.fetch (d1-beta-facade.entry.js:11153:13)',
    message: 'Claimed capability {"can":"space/info","with":"did:key:z6MkvKqE5ft62Uxqts9pmpWEZYqybgkLUMbKt1LgSkK1aNQz"} is invalid\n' +
      "  - Capability can not be (self) issued by 'did:key:z6MkhcbEpJpEvNVDd3n5RurquVdqs5dPU16JDU5VZTDtFgnn'\n" +
      '  - Delegated capability not found\n' +
      '  - Encountered unknown capabilities\n' +
      '    - {"nb":{"link":{"code":514,"version":1,"hash":{"0":18,"1":32,"2":26,"3":58,"4":168,"5":146,"6":239,"7":237,"8":138,"9":216,"10":183,"11":37,"12":84,"13":117,"14":196,"15":48,"16":169,"17":219,"18":238,"19":43,"20":58,"21":6,"22":80,"23":147,"24":195,"25":200,"26":28,"27":71,"28":17,"29":104,"30":151,"31":80,"32":130,"33":75}},"size":47243},"can":"store/add","with":"did:key:z6MkvKqE5ft62Uxqts9pmpWEZYqybgkLUMbKt1LgSkK1aNQz"}'
  },
  error: true,
  stack: 'Unauthorized: Claimed capability {"can":"space/info","with":"did:key:z6MkvKqE5ft62Uxqts9pmpWEZYqybgkLUMbKt1LgSkK1aNQz"} is invalid\n' +
    "  - Capability can not be (self) issued by 'did:key:z6MkhcbEpJpEvNVDd3n5RurquVdqs5dPU16JDU5VZTDtFgnn'\n" +
    '  - Delegated capability not found\n' +
    '  - Encountered unknown capabilities\n' +
    '    - {"nb":{"link":{"code":514,"version":1,"hash":{"0":18,"1":32,"2":26,"3":58,"4":168,"5":146,"6":239,"7":237,"8":138,"9":216,"10":183,"11":37,"12":84,"13":117,"14":196,"15":48,"16":169,"17":219,"18":238,"19":43,"20":58,"21":6,"22":80,"23":147,"24":195,"25":200,"26":28,"27":71,"28":17,"29":104,"30":151,"31":80,"32":130,"33":75}},"size":47243},"can":"store/add","with":"did:key:z6MkvKqE5ft62Uxqts9pmpWEZYqybgkLUMbKt1LgSkK1aNQz"}\n' +
    '    at Mh (d1-beta-facade.entry.js:7203:22)\n' +
    '    at async Object.info (d1-beta-facade.entry.js:8206:11)\n' +
    '    at async dx (d1-beta-facade.entry.js:8148:12)\n' +
    '    at async lx (d1-beta-facade.entry.js:8136:12)\n' +
    '    at async fx (d1-beta-facade.entry.js:8130:42)\n' +
    '    at async fg (d1-beta-facade.entry.js:9039:11)\n' +
    '    at async Bo.fetch (d1-beta-facade.entry.js:3685:17)\n' +
    '    at async Object.fetch (d1-beta-facade.entry.js:11153:13)',
  message: 'Claimed capability {"can":"space/info","with":"did:key:z6MkvKqE5ft62Uxqts9pmpWEZYqybgkLUMbKt1LgSkK1aNQz"} is invalid\n' +
    "  - Capability can not be (self) issued by 'did:key:z6MkhcbEpJpEvNVDd3n5RurquVdqs5dPU16JDU5VZTDtFgnn'\n" +
    '  - Delegated capability not found\n' +
    '  - Encountered unknown capabilities\n' +
    '    - {"nb":{"link":{"code":514,"version":1,"hash":{"0":18,"1":32,"2":26,"3":58,"4":168,"5":146,"6":239,"7":237,"8":138,"9":216,"10":183,"11":37,"12":84,"13":117,"14":196,"15":48,"16":169,"17":219,"18":238,"19":43,"20":58,"21":6,"22":80,"23":147,"24":195,"25":200,"26":28,"27":71,"28":17,"29":104,"30":151,"31":80,"32":130,"33":75}},"size":47243},"can":"store/add","with":"did:key:z6MkvKqE5ft62Uxqts9pmpWEZYqybgkLUMbKt1LgSkK1aNQz"}'
}
```

**Comment by hugomrdias** [comment]
- [ ] add test for derived caps like space/info from store/add
- [ ] check if the fake rpc route fixes this
- [ ] check ucanto for permanent fix
