### ISSUE TITLE
Access API - Auth Flow and Space registration Error

### ISSUE THREAD

**Issue by flea89** [web3-storage/w3protocol#280]
```
��dnameuHandlerExecutionErrorecause�dnamegD1ErrorestackyD1Error: Error: ERROR 9015: SQL engine error: failed to read next row: NOT NULL constraint failed: spaces.metadata (undefined)
    at Ps.create (d1-beta-facade.entry.js:10922:23)
    at async d1-beta-facade.entry.js:9135:24
    at async Ox (d1-beta-facade.entry.js:8274:12)
    at async Ix (d1-beta-facade.entry.js:8262:12)
    at async Bx (d1-beta-facade.entry.js:8256:42)
    at async km (d1-beta-facade.entry.js:9182:11)
    at async No.fetch (d1-beta-facade.entry.js:3685:17)
    at async Object.fetch (d1-beta-facade.entry.js:11332:13)gmessagexuError: ERROR 9015: SQL engine error: failed to read next row: NOT NULL constraint failed: spaces.metadata (undefined)eerror�estacky�HandlerExecutionError: service handler {can: "voucher/redeem"} error: Error: ERROR 9015: SQL engine error: failed to read next row: NOT NULL constraint failed: spaces.metadata (undefined)
    at Ox (d1-beta-facade.entry.js:8276:13)
    at async Ix (d1-beta-facade.entry.js:8262:12)
    at async Bx (d1-beta-facade.entry.js:8256:42)
    at async km (d1-beta-facade.entry.js:9182:11)
    at async No.fetch (d1-beta-facade.entry.js:3685:17)
    at async Object.fetch (d1-beta-facade.entry.js:11332:13)gmessagex�service handler {can: "voucher/redeem"} error: Error: ERROR 9015: SQL engine error: failed to read next row: NOT NULL constraint failed: spaces.metadata (undefined)jcapability�ccannvoucher/redeemdwithx8did:key:z6MkwTYX2JHHd8bmaEuDdS1LJjrpFspirjDcQ4DvAiDP49Gm
```

**Comment by hugomrdias** [comment]
which package are you using to call voucher/redeem ?

**Comment by flea89** [comment]
Using [w3ui/next](https://github.com/web3-storage/w3ui/tree/next)
