### ISSUE TITLE
create single api endpoint for all capabilities

### ISSUE THREAD

**Issue by gobengo** [web3-storage/w3protocol#325]

**Comment by gobengo** [comment]
this is a little related to https://github.com/web3-storage/w3protocol/issues/182

**Comment by gobengo** [comment]
#status you can now issue `store/list` invocations against access-api
[test here](https://github.com/gobengo/monorepo/blob/997cf85472a2f887d5a3ac60dd1127fa6f98de5a/experiments/w3protocol-test/src/w3protocol.test.ts#L16)

`store/add` or other upload-api service methods that validate ucan proofs error like this:
<details>
<summary>error from <a href="https://github.com/gobengo/monorepo/pull/7/files#diff-706e9ee739c12b0b8ca50cd72c2c6708c04c0bf40184239b5b94756a5708c0ceR99">testing store/add against staging access-api using upload-client</a></summary>
<pre>
    # error uploading file
    # error cause {
    #   name: 'Error',
    #   error: true,
    #   stack: 'Error: did:web:staging.web3.storage is not delegated capability store/add on did:key:z6MkoeDLAk1UP48Dc2FT3JdD9G8vB4vnEaeFQr5QVSVf2SJv\\n' +
    #     '    at null.<anonymous> (/upload-api/service/store/add.js:36:16)\\n' +
    #     '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n' +
    #     '    at null.invoke2 (/node_modules/@ucanto/server/src/server.js:129:14)\\n' +
    #     '    at null.execute2 (/node_modules/@ucanto/server/src/server.js:90:18)\\n' +
    #     '    at null.handle (/node_modules/@ucanto/server/src/server.js:71:18)\\n' +
    #     '    at null.ucanInvocationRouter (/upload-api/functions/ucan-invocation-router.js:87:20)\\n' +
    #     '    at Runtime.handler (/node_modules/src/awslambda.ts:332:1)',
    #   message: 'did:web:staging.web3.storage is not delegated capability store/add on did:key:z6MkoeDLAk1UP48Dc2FT3JdD9G8vB4vnEaeFQr5QVSVf2SJv'
    # }
    # Subtest: w3protocol-test can upload file
</pre>
</details>

Getting that to work will require https://github.com/web3-storage/ucanto/issues/195

**Comment by gobengo** [comment]
#status I will update it to use new ucanto functionality to do the proxying without issuing a new delegation - https://github.com/web3-storage/w3protocol/issues/383

**Comment by gobengo** [comment]
#status In general after above work, you should be able to issue ucan invocations only against the deployed access-api. If they are `store/*` or `upload/*` invocations, they will be proxied to be handled by the upload-api running on aws.
This was the gist of how @Gozala and I decided to do it (especially at the time in January).
