### ISSUE TITLE
error invoking store/list through access-api (proxying to upload-api)

### ISSUE THREAD

**Issue by gobengo** [web3-storage/w3protocol#359]
Motivation:
* discovered while testing #325 

When trying to invoke access-api staging with a `can: "store/list"` invocation, I see this error from the upstream upload-api
```
# testing aud=did:web:staging.web3.storage url=https://w3access-staging.protocol-labs.workers.dev/
    # unexpected result from store/list invocation {
    #   name: 'HandlerExecutionError',
    #   cause: {
    #     name: 'TypeError',
    #     stack: 'TypeError: Illegal invocation\\n' +
    #       '    at dN.request (d1-beta-facade.entry.js:14579:24)\\n' +
    #       '    at WN (d1-beta-facade.entry.js:15030:61)\\n' +
    #       '    at async Object.<anonymous> (d1-beta-facade.entry.js:15037:132)\\n' +
    #       '    at async IB (d1-beta-facade.entry.js:14077:12)\\n' +
    #       '    at async AB (d1-beta-facade.entry.js:14065:12)\\n' +
    #       '    at async TB (d1-beta-facade.entry.js:14059:42)\\n' +
    #       '    at async PO (d1-beta-facade.entry.js:15097:11)\\n' +
    #       '    at async ed.fetch (d1-beta-facade.entry.js:9434:17)\\n' +
    #       '    at async Object.fetch (d1-beta-facade.entry.js:20183:13)',
    #     message: 'Illegal invocation'
    #   },
    #   error: true,
    #   stack: 'HandlerExecutionError: service handler {can: "store/list"} error: Illegal invocation\\n' +
    #     '    at IB (d1-beta-facade.entry.js:14079:13)\\n' +
    #     '    at async AB (d1-beta-facade.entry.js:14065:12)\\n' +
    #     '    at async TB (d1-beta-facade.entry.js:14059:42)\\n' +
    #     '    at async PO (d1-beta-facade.entry.js:15097:11)\\n' +
    #     '    at async ed.fetch (d1-beta-facade.entry.js:9434:17)\\n' +
    #     '    at async Object.fetch (d1-beta-facade.entry.js:20183:13)',
    #   message: 'service handler {can: "store/list"} error: Illegal invocation',
    #   capability: {
    #     can: 'store/list',
    #     with: 'did:key:z6Mkm46voCRFK8cxifj98D4mSdP1d6xwWWCtMKsB3YcUGt8c'
    #   }
    # }
```

**Comment by gobengo** [comment]
It would be a little helpful if upload-api stack traces used source maps

**Comment by gobengo** [comment]
I added a unit test for the ucanto proxy that attempts a reduced test case for what I think is happening when the OP error happens, specifically:
* uses same `store/list` capability definition as upload-api
* uses http ucanto transport in connections

https://github.com/web3-storage/w3protocol/pull/360/files#diff-9a0b1851ef99b18fa05356dae74d7db158f89ac19e6e243038dda890fbb0783eR237

Unfortunately I can't reproduce this error. Going to sleep on it

**Comment by gobengo** [comment]
thinking it's more likely that somewhere in access-api is calling `globalThis.fetch` with some other `this` than `globalThis`

**Comment by gobengo** [comment]
The `TypeError: Illegal invocation` seems like it could be caused by cloudflare's `globalThis.fetch` being called without `this` bound to `globalThis`. https://stackoverflow.com/questions/44720448/fetch-typeerror-failed-to-execute-fetch-on-window-illegal-invocation

**Comment by gobengo** [comment]
That resolved the issue when invoking `can=store/list aud=did:web:staging.web3.storage` through `url=https://w3access-staging.protocol-labs.workers.dev/version`
https://github.com/gobengo/monorepo/actions/runs/3952405802/jobs/6767435499#step:6:20
