### ISSUE TITLE
error result invoking access/claim against staging: 'TypeError: Input should be a non-empty Uint8Array.\n' 

### ISSUE THREAD

**Issue by gobengo** [web3-storage/w3protocol#471]
Discovered While Testing
* https://github.com/gobengo/w3protocol-test/pull/6

```
    ok 7 - can invoke access/authorize against staging # SKIP
      ---
      duration_ms: 0.077875
      ...
    claimResult {
      name: 'HandlerExecutionError',
      cause: {
        name: 'TypeError',
        stack: 'TypeError: Input should be a non-empty Uint8Array.\n' +
          '    at Kl (d1-beta-facade.entry.js:15342:11)\n' +
          '    at AW (d1-beta-facade.entry.js:20990:11)\n' +
          '    at _a56.find (d1-beta-facade.entry.js:20974:13)\n' +
          '    at async HU (d1-beta-facade.entry.js:15567:18)\n' +
          '    at async d1-beta-facade.entry.js:15584:41\n' +
          '    at async EB (d1-beta-facade.entry.js:14474:12)\n' +
          '    at async vB (d1-beta-facade.entry.js:14462:12)\n' +
          '    at async bB (d1-beta-facade.entry.js:14456:42)\n' +
          '    at async YC (d1-beta-facade.entry.js:15634:11)\n' +
          '    at async bd.fetch (d1-beta-facade.entry.js:9706:17)',
        message: 'Input should be a non-empty Uint8Array.'
      },
      error: true,
      stack: 'HandlerExecutionError: service handler {can: "access/claim"} error: Input should be a non-empty Uint8Array.\n' +
        '    at EB (d1-beta-facade.entry.js:14476:13)\n' +
        '    at async vB (d1-beta-facade.entry.js:14462:12)\n' +
        '    at async bB (d1-beta-facade.entry.js:14456:42)\n' +
        '    at async YC (d1-beta-facade.entry.js:15634:11)\n' +
        '    at async bd.fetch (d1-beta-facade.entry.js:9706:17)\n' +
        '    at async Object.fetch (d1-beta-facade.entry.js:21017:13)',
      message: 'service handler {can: "access/claim"} error: Input should be a non-empty Uint8Array.',
      capability: {
        can: 'access/claim',
        with: 'did:key:z6MkkUymFxGqXWRqFNiaU4jCa2efexfDCNADqD7sQK3RbU2j'
      }
    }
```

**Comment by gobengo** [comment]
The good news is that this error is after the one that was happening due to https://github.com/web3-storage/w3protocol/issues/464
Which I did a workaround for last night.

**Comment by gobengo** [comment]
after #478 I think this is fixed!! https://github.com/gobengo/w3protocol-test/actions/runs/4327822197/jobs/7556881763#step:6:57
